name: Build and test

on: [push, pull_request]

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        ocaml: [4.14.3, 5.4.1]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create `dune-workspace.ci`
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (ocaml (= %s))))\n' ${{ matrix.ocaml }} >dune-workspace.ci

      - name: Use dune
        uses: ocaml-dune/setup-dune@v2
        with:
          version: latest
          workspace: dune-workspace.ci
          cache-prefix: v1-${{ matrix.ocaml }}
          display: short

